llm_provider: ollama  # options: ollama, gemini

gemini:
  api_key: 
  model:

ollama:
  base_url: http://localhost:11434/api/chat
  model: qwen3  # 在这里换自己的模型

mcpServers:
  qieman: "https://stargate.yingmi.com/mcp/sse?apiKey=<YOUR API KEY>"  # 前往 https://qieman.com/mcp/service-ativation 免费申请
  finmcp:     
    url: "http://localhost:3000/mcp"
    token: "<YOUR TOKEN>"  # 前往 https://tushare.pro/ 获取
